@host = http://44.202.33.23:5000
@host = http://localhost:5001
@host = https://pasteleria-rag-chat.onrender.com

###
curl {{host}}/health

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"hola"}' \
{{host}}/ask-model-history

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"qué productos tienen"}' \
{{host}}/ask-model-history

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Qué es la pastelería la palmera"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Hablame de la pastelería"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Cuál es la dirección de la pastelería"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"quiero saber la dirección de la pastelería"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Cuál es el horario de atención de la pastelería"}' \
{{host}}/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Quiero devolver un producto"}' \
{{host}}/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Tiene productos light"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Qué productos tienes"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"me gustaría saber los procutos que tienes"}' \
{{host}}/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Qué tortas tienes"}' \
{{host}}/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"cuánto cuesta la torta de turron mango"}' \
{{host}}/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"cuánto cuesta la torta glamur"}' \
{{host}}/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"qué porsiones tienes de la torta glamur"}' \
{{host}}/ask

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"Le quedan tortas africana?"}' \
{{host}}/ask-model

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"cuáles son las sucursales"}' \
{{host}}/ask-model

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"qué tortas de chocolate tienes"}' \
{{host}}/ask

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"qué productos de cocktel tienes"}' \
{{host}}/ask-model

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"¿qué productos de coctel tienen?"}' \
{{host}}/ask

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"¿qué productos de cocktail tienen?"}' \
{{host}}/ask

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"tiempo de preparación de tortas"}' \
{{host}}/rerank

###
curl -X POST \
    -H 'Content-Type: application/json' \
    -H 'sessionId: {{$timestamp}}' \
    -d '{"query":"tiempo de entrega de torta"}' \
{{host}}/ask