@host = https://pasteleria-rag-api.onrender.com
@host = http://44.202.33.23:5000
@host = http://localhost:5000

###
curl {{host}}/helth

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"hola"}' \
{{host}}/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Qué es la pastelería la palmera"}' \
http://localhost:5000/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Hablame de la pastelería"}' \
http://localhost:5000/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Cuál es la dirección de la pastelería"}' \
http://localhost:5000/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"quiero saber la dirección de la pastelería"}' \
http://localhost:5000/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Cuál es el horario de atención de la pastelería"}' \
http://44.202.33.23:5000/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Quiero devolver un producto"}' \
http://localhost:5000/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Tiene productos light"}' \
http://localhost:5000/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Qué productos tienes"}' \
http://localhost:5000/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"me gustaría saber los procutos que tienes"}' \
http://localhost:5000/ask-model

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"Qué tortas tienes"}' \
http://localhost:5000/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"cuánto cuesta la torta de turron mango"}' \
http://localhost:5000/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"cuánto cuesta la torta glamur"}' \
http://localhost:5000/ask

###

curl -X POST \
    -H 'Content-Type: application/json' \
    -d '{"query":"qué porsiones tienes de la torta glamur"}' \
http://localhost:5000/ask